/**
 * @author Onur Akpolat <onurakpolat@gmail.com>
 */

package main

const (
	tapglueText = `

88888888888                         888                          .d8888b.                                             
    888                             888                         d88P  Y88b                                            
    888                             888                         Y88b.                                                 
    888   8888b.  88888b.   .d88b.  888 888  888  .d88b.         "Y888b.    .d88b.  888d888 888  888  .d88b.  888d888 
    888      "88b 888 "88b d88P"88b 888 888  888 d8P  Y8b           "Y88b. d8P  Y8b 888P"   888  888 d8P  Y8b 888P"   
    888  .d888888 888  888 888  888 888 888  888 88888888             "888 88888888 888     Y88  88P 88888888 888     
    888  888  888 888 d88P Y88b 888 888 Y88b 888 Y8b.           Y88b  d88P Y8b.     888      Y8bd8P  Y8b.     888     
    888  "Y888888 88888P"   "Y88888 888  "Y88888  "Y8888         "Y8888P"   "Y8888  888       Y88P    "Y8888  888     
                  888           888                                                                                   
                  888      Y8b d88P                                                                                   
                  888       "Y88P"
     
  	`
	tapglueLogo = `
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhso//..            .-/+oyhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNho:.                              -/shNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMmy/.       .:+oyhddNNNNNNNNNNddyyo+:.       -/yNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNh+.'    '-+sdNNMMMMMMMMMMMMMMMMMMMMMMMMNNds+-'    '-odMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMd+'    ':odNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdo:'    .+dMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNo-'   ./hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh/.   '-yNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMd+.   '/hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh/'   .oNMMMMMMMMMMMMMMM
MMMMMMMMMMMMMd/'   -omMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmo-   .sNMMMMMMMMMMMMM
MMMMMMMMMMMN+'   -yNMMMMMMMMMMMMMMNmmdhhhyyys++++++++++yyyyhhhmmNNMMMMMMMMMMMMMMNy-   .sNMMMMMMMMMMM
MMMMMMMMMMy.   .sNMMMMMMMMMNdhs+:-.'''''                   '''''..::+shmNMMMMMMMMMNs.   -hMMMMMMMMMM
MMMMMMMMm/'  '+mMMMMMMMMMh/.'                                          '-+hMMMMMMMMMm+'  '+NMMMMMMMM
MMMMMMMd.   .hMMMMMMMMMM+                                                 'oMMMMMMMMMMh.   -dMMMMMMM
MMMMMMh'   /NMMMMMMMMMMM.                                                  .MMMMMMMMMMMN/   .hMMMMMM
MMMMMy'  'sMMMMMMMMMMMMM.   :-.'                                    '.-.   .MMMMMMMMMMMMMs   'hMMMMM
MMMMy'  'yMMMMMMMMMMMMMM.   mNmd/                       '----::+osyhdmMo   .MMMMMMMMMMMMMMs'  'hMMMM
MMMd'   sMMMMMMMMMMMMMMM.   mMMMh                       yNNNNMMMMMMMMMMo   .MMMMMMMMMMMMMMMs   'dMMM
MMm.   oMMMMMMMMMMMMMMMM.   mMMMd                      .mMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMMMMo   .NMM
MM:   :MMMMMMMMMMMMMMMMM.   mMMMd              '.'   ':mMMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMMMMM:   +MM
Mh   'mMMMMMMMMMMMMMMMMM.   mMMMd              :NdhhhmMMMMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMMMMMm'   dM
M-   oMMMMMMMMMMMMMMMMMM.   mMMMM.             +MMMMMMMMMMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMMMMMMo   :M
d   'NMMMMMMMMMMMMMMMMMM.   mMMMMy'           -mMMMMMMMMMMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMMMMMMN'   d
o   /MMMMMMMMMMMMMMMMMMM.   mMMMMMmo.'    '':sMMMMMMMMMMMMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMMMMMMM/   o
.   hMMMMMMMMMMMMMMMMMMM.   mMMMMNmMMNhhhhmNMMMMMMMMMMMMMMMMMMMMMmNMMMMo   .MMMMMMMMMMMMMMMMMMMh   .
    NMMMMMMMMMMMMMMMMMMM.   mMMMN: -/ohdNMMMMMMMMMMMMMMMMMMNdyo/. :MMMMo   .MMMMMMMMMMMMMMMMMMMN    
    MMMMMMMMMMMMMMMMMMMM.   mMMMNho:'    '..////+oo/////..'    ':ohNMMMo   .MMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMM.   mMMMMMMMMNdyso+/-..........:/+osymNMMMMMMMMo   .MMMMMMMMMMMMMMMMMMMM    
    MMMMMMMMMMMMMMMMMMMM.   mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMMMMMMMM    
    NMMMMMMMMMMMMMMMMMMM.   mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMMMMMMMN    
'   hMMMMMMMMMMMMMMMMMMM.   mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMMMMMMMh   '
+   +MMMMMMMMMMMMMMMMMMM.   mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMMMMMMM+   o
d   'NMMMMMMMMMMMMMMMMMM.   mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMMMMMMN'   d
M.   oMMMMMMMMMMMMMMMMMM.   mMMMMy/shmMMMMMMMMMMMMMMMMMMMMMMMMmhs/yMMMMo   .MMMMMMMMMMMMMMMMMMo   -M
Mh   'mMMMMMMMMMMMMMMMMM.   mMMMN:. ''.:+osyhhhmmmmmdhhhsso/:.'' .:NMMMo   .MMMMMMMMMMMMMMMMMm'   hM
MM:   :MMMMMMMMMMMMMMMMM.   mMMMMNNdyo/:-.'''  ''''''  '''.-:/oydNNMMMMo   .MMMMMMMMMMMMMMMMM:   :MM
MMm.   oMMMMMMMMMMMMMMMM.   mMMMMMMMMMMNNNmmdhhhhhhhhhhdmmNNNMMMMMMMMMMo   .MMMMMMMMMMMMMMMMo   .mMM
MMMh'   yMMMMMMMMMMMMMMM.   mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMMMy   'dMMM
MMMMy'  'yMMMMMMMMMMMMMM.   mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMMy'  'yMMMM
MMMMMy'  'sMMMMMMMMMMMMM.   mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo   .MMMMMMMMMMMMMs'  'yMMMMM
MMMMMMy'   /NMMMMMMMMMMM.   mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo   .MMMMMMMMMMMN/   'hMMMMMM
MMMMMMMd.   -hMMMMMMMMMM-   :ohmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmho-   /MMMMMMMMMMh.   -dMMMMMMM
MMMMMMMMm/   '+mMMMMMMMMd:'    '.:/oshhmmmNNNNNNNNNNNNNNNNmmdhho+/-.'    ':NMMMMMMMMm+'  '/NMMMMMMMM
MMMMMMMMMMs.   .sNMMMMMMMNhs/-''       '''....-------.....'''      ''.-/ydMMMMMMMMNs.   .hMMMMMMMMMM
MMMMMMMMMMMN+'   -yNMMMMMMMMMMmdhs++:-..'''''          '''''..-:++yhdNMMMMMMMMMMNy-   'oNMMMMMMMMMMM
MMMMMMMMMMMMMd/'   -omMMMMMMMMMMMMMMMMMNmmmmhhhhhhhhhhhhmmmmMMMMMMMMMMMMMMMMMMmo-   '/dMMMMMMMMMMMMM
MMMMMMMMMMMMMMMd/'   '/hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh/'   .+dMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNo-'   ./hNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNh/.   '-oNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMd+'    ':odNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdo:'    '+dMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNh+.'    '-+sdNNMMMMMMMMMMMMMMMMMMMMMMMMNNds+-'    '.+hNMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMmy/.       .:+oyhddNNNNNNNNNNddyyo+:.       ./ymMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmho:.                              .:ohNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhs+/:..            ..//oshmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
`
)

// TapglueText gets the tapglue text
func TapglueText() string {
	return tapglueText
}

// TapglueLogo gets the tapglue logo
func TapglueLogo() string {
	return tapglueLogo
}
