export default {
  ANALYTICS: 'analytics',
  APP: 'app/:id',
  APP_DASHBOARD: 'dashboard',
  APP_SETTINGS: 'settings',
  CREATE: 'create',
  APPS: 'apps',
  APPS_CREATE: 'create',
  APPS_DELETE: ':id/delete',
  APPS_EDIT: ':id/edit',
  APPS_LIST: '',
  APPS_SHOW: ':id',
  AUTH: 'auth',
  AUTH_LOGIN: '/login',
  AUTH_LOGOUT: '/logout',
  AUTH_SIGNUP: '/signup',
  CONSOLE: '/',
  DASHBOARD: 'dashboard',
  MEMBERS: 'members',
  MEMBERS_CREATE: 'create',
  MEMBERS_DELETE: ':id/delete',
  MEMBERS_EDIT: ':id/edit',
  MEMBERS_LIST: '',
  MEMBERS_SHOW: ':id',
  ONBOARDING: '/onboarding',
  ORG: 'org'
}
